---
- name: Install NPM
  become: yes
  apt:
    name: npm
    update_cache: yes
    state: latest

- name: Install nvm
  become: yes
  npm:
    name: n
    global: yes

- name: Install nodejs v13.8.0
  become: yes
  command: n 13.8.0

- name: Installing PM2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present