---
- name: Install npm and nodejs
  become: yes
  shell: |
    apt install -y npm
    npm install --global n
    n 13.8.0

- name: Installing PM2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
